// <auto-generated />
using System;
using Lexi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lexi.Data.Migrations
{
    [DbContext(typeof(LexiDbContext))]
    [Migration("20260916085057_AddClientTrialLock")]
    partial class AddClientTrialLock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lexi.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Lexi.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CodeRedeemed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyGoal")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeviceToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TrialLocked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DeviceToken")
                        .IsUnique();

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Lexi.Models.ClientStar", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.HasKey("ClientId", "WordId");

                    b.ToTable("client_word_stars", (string)null);
                });

            modelBuilder.Entity("Lexi.Models.ClientWordProgress", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.Property<int>("Correct")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Due")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Ef")
                        .HasColumnType("double precision");

                    b.Property<int>("Ivl")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Last")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Wrong")
                        .HasColumnType("integer");

                    b.HasKey("ClientId", "WordId");

                    b.HasIndex("WordId");

                    b.HasIndex("ClientId", "Due");

                    b.ToTable("client_word_progress", (string)null);
                });

            modelBuilder.Entity("Lexi.Models.DailyBlockActivity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Block")
                        .HasColumnType("text");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("LastWordId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientId", "Level", "Date", "Block");

                    b.ToTable("client_daily_block_activity", (string)null);
                });

            modelBuilder.Entity("Lexi.Models.OneTimeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsedByClientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("UsedByClientId");

                    b.ToTable("one_time_codes", (string)null);
                });

            modelBuilder.Entity("Lexi.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExampleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExampleRu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ipa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WordText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("WordText");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("Lexi.Models.ClientWordProgress", b =>
                {
                    b.HasOne("Lexi.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lexi.Models.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lexi.Models.OneTimeCode", b =>
                {
                    b.HasOne("Lexi.Models.Client", "UsedByClient")
                        .WithMany()
                        .HasForeignKey("UsedByClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsedByClient");
                });
#pragma warning restore 612, 618
        }
    }
}
